import React, { useState, useCallback } from 'react';
import { Job, ClientReceipt } from '../types';
import { generateClientReceipt, getClientReceipt, markReceiptSent } from '../lib/db';
import { getReportUrl } from '../lib/redirects';

interface ClientReceiptViewProps {
  job: Job;
  onClose: () => void;
}

/**
 * ClientReceiptView - Displays a client-facing receipt for completed jobs
 *
 * For self-employed technicians, this provides:
 * - Professional proof-of-work document
 * - Evidence summary (photos, signature, seal)
 * - Payment information
 * - Shareable via copy, email, SMS
 */
const ClientReceiptView: React.FC<ClientReceiptViewProps> = ({ job, onClose }) => {
  const [receipt, setReceipt] = useState<ClientReceipt | null>(() => {
    // Try to get existing receipt or generate new one
    const existing = getClientReceipt(job.id);
    if (existing) return existing;
    if (job.sealedAt) {
      return generateClientReceipt(job);
    }
    return null;
  });

  const [shareMessage, setShareMessage] = useState<string | null>(null);

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-GB', {
      weekday: 'long',
      day: 'numeric',
      month: 'long',
      year: 'numeric'
    });
  };

  const formatTime = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleTimeString('en-GB', {
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const handleCopyReceipt = useCallback(() => {
    if (!receipt) return;

    const receiptText = `
JobProof - Work Completion Receipt
===================================

Receipt ID: ${receipt.id.substring(0, 8).toUpperCase()}
Date: ${formatDate(receipt.work_date)}

CLIENT
${receipt.client_name}
${receipt.client_address || ''}

WORK COMPLETED
${receipt.job_title}
${receipt.job_description || ''}

Location: ${receipt.work_location}
${receipt.work_location_w3w ? `W3W: ${receipt.work_location_w3w}` : ''}

EVIDENCE SUMMARY
- Photos captured: ${receipt.photos_count}
- Client signature: ${receipt.has_signature ? 'Yes' : 'No'}
${receipt.signer_name ? `- Signed by: ${receipt.signer_name}` : ''}
${receipt.sealed_at ? `- Sealed: ${formatDate(receipt.sealed_at)} at ${formatTime(receipt.sealed_at)}` : ''}

${receipt.amount ? `AMOUNT: £${receipt.amount.toFixed(2)}` : ''}

Verification URL: ${getReportUrl(job.id)}

This receipt was generated by JobProof.
Evidence is cryptographically sealed and verifiable.
    `.trim();

    navigator.clipboard.writeText(receiptText);
    markReceiptSent(receipt.id, 'copy');
    setShareMessage('Receipt copied to clipboard!');
    setTimeout(() => setShareMessage(null), 3000);
  }, [receipt, job.id]);

  const handleShareReceipt = useCallback(async () => {
    if (!receipt) return;

    const shareData = {
      title: `Work Receipt - ${receipt.job_title}`,
      text: `Work completed for ${receipt.client_name} on ${formatDate(receipt.work_date)}. View sealed evidence report:`,
      url: getReportUrl(job.id)
    };

    if (navigator.share) {
      try {
        await navigator.share(shareData);
        markReceiptSent(receipt.id, 'share');
        setShareMessage('Receipt shared!');
        setTimeout(() => setShareMessage(null), 3000);
      } catch (err) {
        if ((err as Error).name !== 'AbortError') {
          console.error('Share failed:', err);
        }
      }
    } else {
      handleCopyReceipt();
    }
  }, [receipt, job.id, handleCopyReceipt]);

  if (!receipt) {
    return (
      <div className="fixed inset-0 z-50 bg-slate-950/95 backdrop-blur-xl flex flex-col animate-in">
        <header className="px-6 py-4 border-b border-white/10 flex items-center justify-between">
          <h1 className="text-xl font-black text-white uppercase tracking-tight">Client Receipt</h1>
          <button
            onClick={onClose}
            className="size-10 rounded-full bg-white/5 flex items-center justify-center text-slate-400 hover:text-white transition-colors"
          >
            <span className="material-symbols-outlined">close</span>
          </button>
        </header>
        <div className="flex-1 flex items-center justify-center p-6">
          <div className="text-center">
            <span className="material-symbols-outlined text-6xl text-slate-600 mb-4">receipt_long</span>
            <p className="text-slate-400 text-sm">Receipt will be generated after job is sealed</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/95 backdrop-blur-xl flex flex-col animate-in">
      {/* Header */}
      <header className="px-6 py-4 border-b border-white/10 flex items-center justify-between">
        <div>
          <h1 className="text-xl font-black text-white uppercase tracking-tight">Client Receipt</h1>
          <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest mt-0.5">
            ID: {receipt.id.substring(0, 8).toUpperCase()}
          </p>
        </div>
        <button
          onClick={onClose}
          className="size-10 rounded-full bg-white/5 flex items-center justify-center text-slate-400 hover:text-white transition-colors"
        >
          <span className="material-symbols-outlined">close</span>
        </button>
      </header>

      {/* Receipt Content */}
      <div className="flex-1 overflow-y-auto p-6">
        {/* Share Message */}
        {shareMessage && (
          <div className="bg-success/10 border border-success/20 rounded-2xl p-4 mb-6 animate-in">
            <p className="text-success text-sm font-bold flex items-center gap-2">
              <span className="material-symbols-outlined text-lg">check_circle</span>
              {shareMessage}
            </p>
          </div>
        )}

        {/* Receipt Card */}
        <div className="bg-white rounded-3xl p-6 shadow-2xl max-w-md mx-auto">
          {/* Header */}
          <div className="text-center border-b border-slate-200 pb-4 mb-4">
            <div className="flex items-center justify-center gap-2 mb-2">
              <div className="size-8 bg-primary rounded-lg flex items-center justify-center">
                <span className="material-symbols-outlined text-white text-sm font-black">verified</span>
              </div>
              <span className="text-xl font-black text-slate-900 uppercase tracking-tight">JobProof</span>
            </div>
            <p className="text-[10px] text-slate-500 font-bold uppercase tracking-widest">Work Completion Receipt</p>
          </div>

          {/* Date */}
          <div className="text-center mb-4">
            <p className="text-sm font-bold text-slate-600">{formatDate(receipt.work_date)}</p>
          </div>

          {/* Client Info */}
          <div className="bg-slate-50 rounded-2xl p-4 mb-4">
            <p className="text-[10px] font-black text-slate-600 uppercase tracking-widest mb-1">Client</p>
            <p className="text-sm font-bold text-slate-900">{receipt.client_name}</p>
            {receipt.client_address && (
              <p className="text-xs text-slate-700 mt-1">{receipt.client_address}</p>
            )}
          </div>

          {/* Work Details */}
          <div className="mb-4">
            <p className="text-[10px] font-black text-slate-600 uppercase tracking-widest mb-2">Work Completed</p>
            <p className="text-lg font-black text-slate-900 uppercase tracking-tight">{receipt.job_title}</p>
            {receipt.job_description && (
              <p className="text-xs text-slate-600 mt-2 leading-relaxed">{receipt.job_description}</p>
            )}
          </div>

          {/* Location */}
          <div className="bg-slate-50 rounded-2xl p-4 mb-4">
            <p className="text-[10px] font-black text-slate-600 uppercase tracking-widest mb-1">Location</p>
            <p className="text-sm font-bold text-slate-900">{receipt.work_location}</p>
            {receipt.work_location_w3w && (
              <div className="flex items-center gap-1 mt-1">
                <span className="text-red-500 font-black text-xs">///</span>
                <span className="text-xs text-slate-700">{receipt.work_location_w3w.replace('///', '')}</span>
              </div>
            )}
          </div>

          {/* Evidence Summary */}
          <div className="border border-slate-200 rounded-2xl p-4 mb-4">
            <p className="text-[10px] font-black text-slate-600 uppercase tracking-widest mb-3">Evidence Summary</p>
            <div className="grid grid-cols-2 gap-3 text-sm">
              <div className="flex items-center gap-2">
                <span className="material-symbols-outlined text-primary text-sm">photo_camera</span>
                <span className="text-slate-600">{receipt.photos_count} Photos</span>
              </div>
              <div className="flex items-center gap-2">
                <span className={`material-symbols-outlined text-sm ${receipt.has_signature ? 'text-success' : 'text-slate-400'}`}>
                  signature
                </span>
                <span className="text-slate-600">{receipt.has_signature ? 'Signed' : 'Unsigned'}</span>
              </div>
              {receipt.signer_name && (
                <div className="col-span-2 flex items-center gap-2">
                  <span className="material-symbols-outlined text-slate-400 text-sm">person</span>
                  <span className="text-slate-600">{receipt.signer_name}</span>
                </div>
              )}
            </div>
          </div>

          {/* Seal Status */}
          {receipt.sealed_at && (
            <div className="bg-success/10 border border-success/20 rounded-2xl p-4 mb-4">
              <div className="flex items-center gap-3">
                <div className="size-10 bg-success/20 rounded-full flex items-center justify-center">
                  <span className="material-symbols-outlined text-success font-black">lock</span>
                </div>
                <div>
                  <p className="text-[10px] font-black text-success uppercase tracking-widest">Evidence Sealed</p>
                  <p className="text-xs text-slate-600">
                    {formatDate(receipt.sealed_at)} at {formatTime(receipt.sealed_at)}
                  </p>
                </div>
              </div>
              {receipt.evidence_hash && (
                <p className="text-[8px] font-mono text-slate-600 mt-2 break-all">
                  Hash: {receipt.evidence_hash.substring(0, 32)}...
                </p>
              )}
            </div>
          )}

          {/* Amount */}
          {receipt.amount && (
            <div className="border-t-2 border-dashed border-slate-200 pt-4 mt-4">
              <div className="flex justify-between items-center">
                <p className="text-sm font-black text-slate-700 uppercase">Amount Due</p>
                <p className="text-2xl font-black text-slate-900">
                  £{receipt.amount.toFixed(2)}
                </p>
              </div>
              <p className="text-[10px] text-slate-600 mt-1">Payment status: {receipt.payment_status || 'Pending'}</p>
            </div>
          )}

          {/* Verification Link */}
          <div className="border-t border-slate-200 pt-4 mt-4 text-center">
            <p className="text-[10px] text-slate-600 mb-2">Verify this receipt online</p>
            <p className="text-xs font-mono text-primary break-all">{getReportUrl(job.id)}</p>
          </div>
        </div>
      </div>

      {/* Footer Actions */}
      <footer className="p-6 border-t border-white/10 space-y-3">
        <button
          onClick={handleShareReceipt}
          className="w-full py-5 bg-primary rounded-2xl font-black text-white text-sm uppercase tracking-widest shadow-lg shadow-primary/20 flex items-center justify-center gap-3 transition-all active:scale-98"
        >
          <span className="material-symbols-outlined text-lg">share</span>
          Share with Client
        </button>
        <button
          onClick={handleCopyReceipt}
          className="w-full py-4 bg-white/5 rounded-2xl font-bold text-slate-400 text-xs uppercase tracking-widest hover:text-white transition-colors flex items-center justify-center gap-2"
        >
          <span className="material-symbols-outlined text-sm">content_copy</span>
          Copy Receipt Text
        </button>
      </footer>
    </div>
  );
};

export default ClientReceiptView;
